### NumPy 

- NumPy is a Python library for numerical computing.
- It offers support for large, multi-dimensional arrays and matrices.
- NumPy provides mathematical functions to operate on arrays efficiently.
- Widely used in scientific computing, engineering, data science, and machine learning.
- Key features include multidimensional arrays, array operations, broadcasting, vectorized operations, linear algebra functions, and random number generation.

In [1]:
#import Numpy

import numpy as np

This line imports the NumPy library and assigns it the alias np. The use of the alias np is a standard convention in the Python community when working with NumPy. Once this import statement is executed, you can access NumPy functions and classes by prefixing them with np.

In [2]:
#checking NumPy Version

print (np.__version__)

1.26.4


This statement indicates that you have NumPy version 1.24.3 installed. Verifying the version is important because different versions of a library may introduce new features, bug fixes, or enhancements. Checking the version helps you ensure compatibility with your code and other libraries. Additionally, it enables you to stay informed about updates and potential compatibility issues.

### NumPy array (Ndarray)
 
- Ndarray is the core data type in NumPy.
- It represents n-dimensional arrays.
- Ndarray allows efficient storage and manipulation of multidimensional data.
- NumPy arrays provide optimized mathematical operations.
- They offer enhanced performance compared to Python lists.

In [3]:
# List
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Array from list:")
print(array_from_list)
print(type(array_from_list)) #Check Type array

Array from list:
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Tuple
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print("\nArray from tuple:")
print(array_from_tuple)
print(type(array_from_tuple))# Check Type array


Array from tuple:
[ 6  7  8  9 10]
<class 'numpy.ndarray'>


### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays)

- Arrays can have one or more dimensions.
- One-dimensional arrays are like lists, containing elements arranged in a single row.
- Two-dimensional arrays have rows and columns, forming a grid-like structure.
- Arrays with three or more dimensions add additional layers of complexity, representing higher-dimensional spaces.
- Each dimension adds a level of hierarchy to the array, organizing the data in a structured manner.

In [5]:
# Create 0-Dimension Array

arr = np.array(42)

print("Number of Dimensions :", arr.ndim)

Number of Dimensions : 0


In [6]:
# Create a 1-Dimension Arrays

arr_1 = np.array([1, 2, 3])

print(arr_1)
print("Number of Dimensions :", arr_1.ndim) #Check how many dimensions the arrays have

[1 2 3]
Number of Dimensions : 1


In [7]:
# 2-Dimension Arrays

arr_2 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

print(arr_2)
print("Number of Dimensions :", arr_2.ndim) #Check how many dimensions the arrays have

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Number of Dimensions : 2


In [8]:
# 3-Dimension Arrays

arr_3 = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])

print(arr_3)
print("Number of Dimensions :", arr_3.ndim) #Check how many dimensions the arrays have

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
Number of Dimensions : 3


In [9]:
# 4-Dimension Arrays

arr4 = np.array([[[[2,6,3,1,5], [2,3,1,4,1]], 
                  [[9,8,7,6,5], [4,3,2,1,2]]], 
                 [[[2,5,1,2,4], [6,2,4,2,4]], 
                  [[1,2,6,5,2], [2,5,1,2,4]]]])

print(arr4)
print("Number of Dimensions :", arr4.ndim) #Check how many dimensions the arrays have

[[[[2 6 3 1 5]
   [2 3 1 4 1]]

  [[9 8 7 6 5]
   [4 3 2 1 2]]]


 [[[2 5 1 2 4]
   [6 2 4 2 4]]

  [[1 2 6 5 2]
   [2 5 1 2 4]]]]
Number of Dimensions : 4


#### Create an array with 5 dimensions and verify that it has 5 dimensions

In [10]:
#Create an array with 5 dimensions and verify that it has 5 dimensions
arr = np.array([3,1,2,5], ndmin=5) # specifies that the minimum number of dimensions for the array
print(arr)
print("number of dimensions :", arr.ndim) #Check how many dimensions the arrays have

[[[[[3 1 2 5]]]]]
number of dimensions : 5


### Get a Element From Array

- To access elements from a NumPy array, you use indexes within square brackets [ ].
- Indexes are used to specify the position of the element you want to access in the array.
- Can use one index to access elements in a one-dimensional array, two indexes for a two-dimensional array, and so on according to the desired array dimension.
- Indexes start from 0, meaning the first element has index 0, the second element has index 1, and so on.
- Can also use negative indexes to access elements from the end of the array, with -1 referring to the last element, -2 to the second last, and so on.

In [11]:
# Get the first eLement from the following array

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [12]:
# Get the first and Third eLement and also add them 

arr = np.array([5, 7, 9, 2, 1])

print("First eLement :", arr[0])
print("Third eLement :", arr[2])
print("Result of the addition of First and Third Element :", arr[0] + arr[2])

First eLement : 5
Third eLement : 9
Result of the addition of First and Third Element : 14


In [13]:
# Access the eLement the first row, second column

arr = np.array([[2, 6, 3, 1, 5], [2,3,1,4,1]])

print("2nd element on 1st row:", arr[0, 1]) #[row, element]

2nd element on 1st row: 6


In [14]:
# Access the third element of the second array of the first array

arr = np.array([[[2, 6, 3, 1, 5], [2,3,1,4,1]], [[9, 8, 7, 6, 5], [4,3,2,1,2]]])

print("Third element of the second array of the first array:", arr[1, 0, 2]) #[dim, row, element]

Third element of the second array of the first array: 7


In [15]:
# Print the last element from the 2nd dim

arr = np.array([[2, 6, 3, 1, 5], [2,3,1,4,7]])

print("Last Element from 2nd dim:", arr[1, -1]) #[row, element]

Last Element from 2nd dim: 7


In [16]:
# Gets the fifth element of the first dim in the second array

arr4 = np.array([[[[2,6,3,1,5], [2,3,1,4,1]], 
                  [[9,8,7,6,5], [4,3,2,1,2]]], 
                 [[[2,5,1,2,4], [6,2,4,2,4]], 
                  [[1,2,6,5,2], [2,5,1,2,4]]]])

element = arr4[1, 0, 0, 4] #[dim1, dim2, row, element]
print("The element is:", element)

The element is: 4
